/* eslint-disable @next/next/no-img-element */
"use client";
import Link from "next/link";import {ArrowUp,LoaderCircle,MessageCircle,RotateCcw,X} from "lucide-react";import {FormEvent,useEffect,useRef,useState} from "react";import {usePathname} from "next/navigation";import {chatWithAssistant} from "@/lib/api";
type Message={role:"assistant"|"user";text:string;actions?:{label:string;href:string}[]};
const welcome:Message={role:"assistant",text:"Hi! I’m the UPDATES assistant. Ask me about the latest news, a story’s analysis, sources or privacy."};
export function Chatbot(){const [open,setOpen]=useState(false);const [input,setInput]=useState("");const [loading,setLoading]=useState(false);const [messages,setMessages]=useState<Message[]>([welcome]);const end=useRef<HTMLDivElement>(null);const pathname=usePathname();const topicSlug=pathname.startsWith("/topic/")?decodeURIComponent(pathname.slice(7)):undefined;
 useEffect(()=>{const timer=window.setTimeout(()=>{try{const stored=localStorage.getItem("updates-chat-history");if(stored)setMessages(JSON.parse(stored))}catch{}},0);return()=>window.clearTimeout(timer)},[]);useEffect(()=>{if(open)end.current?.scrollIntoView({behavior:"smooth"})},[messages,open]);
 function save(next:Message[]){setMessages(next);localStorage.setItem("updates-chat-history",JSON.stringify(next.slice(-20)))}
 async function send(text:string){const clean=text.trim();if(!clean||loading)return;const asked=[...messages,{role:"user" as const,text:clean}];save(asked);setInput("");setLoading(true);try{const result=await chatWithAssistant(clean,topicSlug,pathname);save([...asked,{role:"assistant",text:result.answer,actions:result.actions}])}catch{save([...asked,{role:"assistant",text:"I can’t reach the analysis service right now. Please try again in a moment."}])}finally{setLoading(false)}}function submit(event:FormEvent){event.preventDefault();void send(input)}function reset(){save([welcome])}
 return <div className="chatbot"><button className="chatbot-launcher" onClick={()=>setOpen(value=>!value)} aria-label={open?"Close UPDATES assistant":"Open UPDATES assistant"}><img src="/images/updates-chatbot-clean.png?v=2" alt="UPDATES chatbot mascot"/><span><MessageCircle/>Ask UPDATES</span></button>{open&&<section className="chat-window" aria-label="UPDATES assistant"><header><div><img src="/images/updates-chatbot-clean.png?v=2" alt=""/><span><strong>UPDATES Assistant</strong><small><i/> Online · evidence aware</small></span></div><div><button onClick={reset} aria-label="Clear conversation"><RotateCcw/></button><button onClick={()=>setOpen(false)} aria-label="Close chat"><X/></button></div></header><div className="chat-messages">{messages.map((message,index)=><article className={message.role} key={`${message.role}-${index}`}><p>{message.text}</p>{message.actions&&<nav>{message.actions.map(action=><Link href={action.href} key={action.href} onClick={()=>setOpen(false)}>{action.label}</Link>)}</nav>}</article>)}{loading&&<article className="assistant typing"><LoaderCircle className="spin"/> Checking live data…</article>}<div ref={end}/></div><div className="chat-suggestions">{["Latest news","Explain this analysis","Check data sources"].map(label=><button key={label} onClick={()=>void send(label)}>{label}</button>)}</div><form onSubmit={submit}><input value={input} onChange={event=>setInput(event.target.value)} placeholder="Ask about news or analysis…" maxLength={500}/><button disabled={loading||!input.trim()} aria-label="Send message"><ArrowUp/></button></form></section>}</div>}
