"use client";
import Link from "next/link";import {BookOpen,CheckCircle2,Database,Eye,LockKeyhole,MessageCircleQuestion,ShieldCheck,UserRound} from "lucide-react";import {useEffect,useState} from "react";import {Sidebar} from "./Sidebar";import {Topbar} from "./Topbar";
type Section="start"|"analysis"|"privacy"|"faq";const sections=[{id:"start" as Section,label:"Getting started",icon:BookOpen},{id:"analysis" as Section,label:"Reading analysis",icon:Eye},{id:"privacy" as Section,label:"Data privacy",icon:ShieldCheck},{id:"faq" as Section,label:"FAQ",icon:MessageCircleQuestion}];
export function HelpGuidePage(){const [section,setSection]=useState<Section>("start");useEffect(()=>{const timer=window.setTimeout(()=>{if(location.hash==="#privacy")setSection("privacy")},0);return()=>window.clearTimeout(timer)},[]);return <div className="app-shell"><Sidebar active="Help & Guide"/><main className="main help-main"><Topbar/><header className="guide-header"><small>HELP CENTER</small><h1>Help & Guide</h1><p>Understand discovery, live feeds, analysis confidence and privacy safeguards.</p><nav>{sections.map(({id,label,icon:Icon})=><button key={id} className={section===id?"active":""} onClick={()=>{setSection(id);history.replaceState(null,"",id==="privacy"?"#privacy":"/help")}}><Icon/>{label}</button>)}</nav></header>
 {section==="start"&&<section className="guide-content"><h2>Get productive in minutes</h2><p>UPDATES connects each news story to its own evidence-backed analysis.</p><div className="guide-cards"><article><BookOpen/><h3>Discover stories</h3><p>Use Home, category filters, search or Live to find current stories.</p><Link href="/">Open discovery</Link></article><article><Eye/><h3>Open analysis</h3><p>Select Analysis on any live post to inspect sentiment, themes and confidence.</p><Link href="/live">Open live feed</Link></article><article><Database/><h3>Check sources</h3><p>Review connected APIs, models and ingestion jobs before presenting results.</p><Link href="/sources">Open sources</Link></article></div></section>}
 {section==="analysis"&&<section className="guide-content"><h2>How to read an analysis</h2><div className="privacy-stack"><article><Eye/><div><h3>Sentiment and stance</h3><p>Sentiment describes tone; stance describes whether a comment supports, opposes or questions the selected topic. They are calculated separately.</p></div></article><article><Database/><div><h3>Conversation counts</h3><p>The label states whether the count represents social comments, indexed articles or public-attention signals.</p></div></article><article><CheckCircle2/><div><h3>Confidence</h3><p>Confidence reflects sample size, source coverage, signal quality and model certainty. Missing demographics remain unavailable rather than being guessed.</p></div></article></div><Link className="guide-action" href="/methodology">Read full methodology</Link></section>}
 {section==="privacy"&&<section id="privacy" className="guide-content"><h2>Data Privacy</h2><p>Analyze public conversations in aggregate, never surveil individuals.</p><div className="privacy-stack"><article><Database/><div><h3>What we collect</h3><p>Permitted public posts, comments, reactions, timestamps and public news signals. Private messages and content behind a login are excluded.</p><ul><li>Public source records and interactions</li><li>Aggregated sentiment, topic and volume metrics</li><li>Explicit, non-identifying metadata where available</li></ul></div></article><article><Eye/><div><h3>How we use it</h3><p>Data surfaces emerging trends and aggregate patterns. Individual authors are not targeted or assigned private traits.</p><ul><li>Trend and conversation analysis</li><li>Anonymized representative public voices</li><li>Confidence scoring and low-signal down-weighting</li></ul></div></article><article><UserRound/><div><h3>Your rights & anonymization</h3><p>Author identifiers are keyed hashes. Sensitive attributes are not inferred from writing style.</p></div></article><article><LockKeyhole/><div><h3>How we protect it</h3><p>Collection uses approved APIs, restricted administrative endpoints, request limits and minimal retained identifiers.</p></div></article></div></section>}
 {section==="faq"&&<section className="guide-content"><h2>Frequently asked questions</h2><details><summary>Is every number a social-comment count?</summary><p>No. The dashboard explicitly labels comments, article signals and Wikimedia attention evidence.</p></details><details><summary>Why can age or geography be unavailable?</summary><p>Those fields require explicit public metadata. UPDATES does not guess sensitive attributes.</p></details><details><summary>How often does the feed update?</summary><p>The backend discovers and re-analyzes due stories automatically every two hours.</p></details><details><summary>Where can I inspect API health?</summary><p>Open Sources to review connector readiness, model status and ingestion jobs.</p></details></section>}
 </main></div>}
