/* eslint-disable @next/next/no-img-element */
"use client";
import Image from "next/image";import Link from "next/link";
import {BarChart3,ChevronRight,FlaskConical,Globe2,GraduationCap,Landmark,Leaf,MoreHorizontal,RefreshCw,Scale,Users,X} from "lucide-react";
import {useEffect,useMemo,useRef,useState} from "react";
import {stories as fallbackStories} from "@/lib/demo-data";import {getStories,refreshLatestNews} from "@/lib/api";import type {Story} from "@/types";import {Sidebar} from "./Sidebar";import {Topbar} from "./Topbar";import {StoryCard} from "./StoryCard";
const categories=[{name:"All",icon:Globe2},{name:"Protest",icon:Users},{name:"Foreign Affairs",icon:Landmark},{name:"Laws",icon:Scale},{name:"Analysis",icon:BarChart3},{name:"Environment",icon:Leaf},{name:"Science & Tech",icon:FlaskConical},{name:"Education",icon:GraduationCap},{name:"More",icon:MoreHorizontal}];
export function HomePage(){
  const [items,setItems]=useState<Story[]>(fallbackStories);const [category,setCategory]=useState("All");const [showAll,setShowAll]=useState(false);const [refreshing,setRefreshing]=useState(false);const [refreshNote,setRefreshNote]=useState("");const [activeHero,setActiveHero]=useState(0);const [popupIndex,setPopupIndex]=useState(0);const [popupVisible,setPopupVisible]=useState(false);
  const latestId=useRef<string|undefined>(undefined);
  useEffect(()=>{let cancelled=false;async function sync(){try{const fresh=await getStories();if(cancelled)return;const newTop=Boolean(latestId.current&&fresh[0]?.id!==latestId.current);latestId.current=fresh[0]?.id;setItems(fresh);if(newTop){setActiveHero(0);setPopupIndex(0);setPopupVisible(true);setRefreshNote("New story received · analysis is being prepared")}}catch{}}sync();const timer=window.setInterval(sync,15000);const visible=()=>{if(document.visibilityState==="visible")sync()};document.addEventListener("visibilitychange",visible);window.addEventListener("focus",sync);return()=>{cancelled=true;window.clearInterval(timer);document.removeEventListener("visibilitychange",visible);window.removeEventListener("focus",sync)}},[]);
  async function refresh(){setRefreshing(true);setRefreshNote("");try{const result=await refreshLatestNews();setItems(result.stories);setCategory("All");setActiveHero(0);setPopupIndex(0);setPopupVisible(true);setRefreshNote(result.added?`${result.added} recent stories added`:`Already up to date · ${result.received} checked`)}catch{setRefreshNote("Live news source is temporarily unavailable")}finally{setRefreshing(false)}}
  const filtered=useMemo(()=>category==="All"||category==="More"?items:items.filter(item=>item.category===category||(category==="Protest"&&item.category==="India")),[items,category]);const shown=showAll?filtered:filtered.slice(0,12);const heroSlides=useMemo(()=>items.slice(0,5),[items]);const heroIndex=heroSlides.length?activeHero%heroSlides.length:0;const hero=heroSlides[heroIndex]??fallbackStories[0];const remoteHero=/^https?:\/\//.test(hero.image);
  useEffect(()=>{if(heroSlides.length<2)return;const timer=window.setInterval(()=>setActiveHero(current=>(current+1)%heroSlides.length),3000);return()=>window.clearInterval(timer)},[heroSlides.length]);
  useEffect(()=>{if(!items.length)return;const first=window.setTimeout(()=>setPopupVisible(true),900);const timer=window.setInterval(()=>{setPopupIndex(current=>(current+1)%Math.min(items.length,8));setPopupVisible(true)},3500);return()=>{window.clearTimeout(first);window.clearInterval(timer)}},[items.length]);
  const popup=items[popupIndex%Math.max(1,Math.min(items.length,8))];
  return <div className="app-shell"><Sidebar/><main className="main"><Topbar/><section className="hero" aria-roledescription="carousel" aria-label="Latest news">{remoteHero?<img key={hero.id} className="hero-photo" src={hero.image} alt={hero.title}/>:<Image key={hero.id} src={hero.image} alt={hero.title} fill priority sizes="(max-width: 900px) 100vw, 85vw"/>}<div className="hero-wash"/><div className="hero-copy dynamic-hero-copy" key={`copy-${hero.id}`}><h1><span>LATEST</span><br/><em>{hero.category}</em><br/><b>{hero.title}</b></h1><p>{hero.live?"LIVE DEVELOPING STORY":"LATEST VERIFIED COVERAGE"}</p><small>{hero.time.toUpperCase()} · <b>TOPIC-SPECIFIC SIGNALS.</b></small></div><div className="hero-dots">{heroSlides.map((slide,index)=><button key={slide.id} className={index===heroIndex?"active":""} onClick={()=>setActiveHero(index)} aria-label={`Show ${slide.title}`} aria-current={index===heroIndex?"true":undefined}/>)}</div></section><section id="categories" className="categories" aria-label="Topic categories">{categories.map(({name,icon:Icon})=><button className={category===name?"selected":""} onClick={()=>setCategory(name)} key={name}><Icon size={25}/><span>{name}</span></button>)}</section><section id="stories" className="story-section"><div className="section-title"><h2>{category==="All"?"Latest & recommended":category}</h2><div className="section-actions"><button onClick={refresh} disabled={refreshing}><RefreshCw size={12} className={refreshing?"spin":""}/>{refreshing?"Refreshing…":"Refresh latest"}</button><button onClick={()=>setShowAll(value=>!value)}>{showAll?"Show less":"See all"}</button></div></div>{refreshNote&&<p className="refresh-note">{refreshNote}</p>}{shown.length?<div className="story-grid">{shown.map(story=><StoryCard story={story} key={story.id}/>)}</div>:<div className="data-empty"><strong>No stories in this category yet</strong><p>This is a dynamic placeholder ready for content from the backend.</p></div>}<p className="demo-note">Each story opens its own isolated analysis dataset. Empty modules are shown until comments are collected for that story.</p></section>{popup&&popupVisible&&<aside key={`popup-${popup.id}-${popupIndex}`} className="news-popup" role="status" aria-live="polite"><button onClick={()=>setPopupVisible(false)} aria-label="Dismiss update"><X/></button><span><i/> LATEST UPDATE · {popup.time}</span><Link href={popup.topic_slug?`/topic/${popup.topic_slug}`:`/story/${popup.id}`}><strong>{popup.title}</strong><small>Open story analysis <ChevronRight/></small></Link></aside>}</main></div>}
