/* eslint-disable @next/next/no-img-element */
"use client";
import Image from "next/image";import Link from "next/link";
import {BarChart3,Bookmark,Heart,LoaderCircle,MessageCircle,Radio,Share2} from "lucide-react";
import {useEffect,useMemo,useState} from "react";
import {getFeed,setBookmark} from "@/lib/api";import {stories as fallback} from "@/lib/demo-data";import type {Story} from "@/types";import {Sidebar} from "./Sidebar";import {Topbar} from "./Topbar";
type SortMode="top"|"latest";
function LivePost({story}:{story:Story}){const [liked,setLiked]=useState(false);const [saved,setSaved]=useState(Boolean(story.bookmarked));const [shared,setShared]=useState(false);const analysisHref=`/topic/${story.topic_slug??"reservation-protest"}`;const storyHref=`/story/${story.id}`;const remote=/^https?:\/\//.test(story.image);
  async function share(){const url=`${location.origin}${analysisHref}`;if(navigator.share)await navigator.share({title:story.title,url});else await navigator.clipboard.writeText(url);setShared(true);setTimeout(()=>setShared(false),1500)}
  async function save(){const next=!saved;setSaved(next);try{await setBookmark(story.id,next)}catch{const values=JSON.parse(localStorage.getItem("updates-bookmarks")??"[]") as string[];localStorage.setItem("updates-bookmarks",JSON.stringify(next?[...new Set([...values,story.id])]:values.filter(id=>id!==story.id)))}}
  return <article className="live-post"><div className="live-avatar">{story.category.slice(0,1).toUpperCase()}</div><div className="live-post-body"><div className="live-post-meta"><strong>{story.category}</strong><span>@updates_signals</span><i/><span>{story.time}</span>{story.live&&<em><Radio size={11}/> Live</em>}</div><Link href={analysisHref} className="live-post-title">{story.title}</Link><Link href={analysisHref} className="live-post-image">{remote?<img src={story.image} alt={story.title}/>:<Image src={story.image} alt={story.title} fill sizes="(max-width: 760px) 92vw, 720px"/>}</Link><div className="live-post-actions"><Link href={storyHref}><MessageCircle/><span>Discuss</span></Link><button onClick={share}><Share2/><span>{shared?"Copied":"Share signal"}</span></button><button className={liked?"selected":""} onClick={()=>setLiked(value=>!value)}><Heart fill={liked?"currentColor":"none"}/><span>Like</span></button><Link href={analysisHref}><BarChart3/><span>Analysis</span></Link><button className={saved?"selected save-action":"save-action"} onClick={save} aria-label={saved?"Remove bookmark":"Save story"}><Bookmark fill={saved?"currentColor":"none"}/></button></div></div></article>}
export function LiveFeedPage(){const [items,setItems]=useState<Story[]|null>(null);const [sort,setSort]=useState<SortMode>("top");useEffect(()=>{getFeed().then(setItems).catch(()=>setItems(fallback))},[]);const ordered=useMemo(()=>{if(!items)return [];if(sort==="latest")return items;return [...items].sort((a,b)=>Number(Boolean(b.live))-Number(Boolean(a.live))||Number(Boolean(b.topic_slug))-Number(Boolean(a.topic_slug)))},[items,sort]);return <div className="app-shell live-shell"><Sidebar active="Live"/><main className="main live-main"><Topbar compact/><header className="live-feed-header"><span><i/>Live feed</span><div><h1>Top posts right now</h1><p>The most active public stories across connected sources, refreshed as new signals arrive.</p></div><div className="live-sort" role="group" aria-label="Sort live feed"><button className={sort==="top"?"active":""} onClick={()=>setSort("top")}>Top</button><button className={sort==="latest"?"active":""} onClick={()=>setSort("latest")}>Latest</button></div></header>{items===null?<div className="page-state"><LoaderCircle className="spin"/> Loading live feed…</div>:<section className="live-stream">{ordered.map(story=><LivePost story={story} key={story.id}/>)}</section>}</main></div>}
