import type { Story, Topic } from "@/types";
export const stories:Story[] = [
 {id:"1",topic_slug:"reservation-protest",title:"CJP Protest Intensifies Across Multiple States",category:"India",time:"2h ago",image:"/images/real-protest.jpg",live:true},
 {id:"2",topic_slug:"student-community-food-drives",title:"Students Unite for Community Food Drives",category:"India",time:"4h ago",image:"/images/real-food-drive.jpg"},
 {id:"3",topic_slug:"supreme-court-reservation-hearing",title:"Supreme Court Hearing on Reservation Policy",category:"Laws",time:"5h ago",image:"/images/real-supreme-court.jpg"},
 {id:"4",topic_slug:"university-campus-protests",title:"University Campus Protests: Demands & Updates",category:"Education",time:"3h ago",image:"/images/real-campus.jpg"},
 {id:"5",topic_slug:"reservation-debate-un-forum",title:"India Raises Reservation Debate at UN Forum",category:"Foreign Affairs",time:"6h ago",image:"/images/real-un-forum.jpg"},
 {id:"6",topic_slug:"city-wide-protests",title:"City-Wide Protests Disrupt Normal Life",category:"India",time:"1h ago",image:"/images/real-city-protest.jpg"},
 {id:"7",topic_slug:"nationwide-bharat-bandh",title:"Dalit Organisations Call for Nationwide Bharat Bandh",category:"Protest",time:"6h ago",image:"/images/real-bharat-bandh.png"},
 {id:"8",topic_slug:"reservation-framework-bill",title:"New Bill Proposes Changes to Reservation Framework",category:"Laws",time:"8h ago",image:"/images/real-bill.jpg"},
 {id:"9",topic_slug:"aspirants-reservation-debate",title:"Aspirants Speak: The Other Side of the Debate",category:"Opinions",time:"7h ago",image:"/images/real-aspirants.jpg"},
 {id:"10",topic_slug:"reservation-rural-india",title:"How Reservation Impacts Rural India",category:"India",time:"9h ago",image:"/images/real-rural.jpg"},
 {id:"11",topic_slug:"reservation-fact-check",title:"Data Check: Facts vs Claims on Reservations",category:"Analysis",time:"10h ago",image:"/images/real-data-check.jpg"},
 {id:"12",topic_slug:"ground-zero-reservation-voices",title:"Voices from Ground Zero: Stories You Didn't Hear",category:"India",time:"12h ago",image:"/images/real-ground-zero.jpg"},
];
export const reservationTopic:Topic={slug:"reservation-protest",title:"Latest Reservation Protest",subtitle:"Public sentiment & conversation analysis",totalConversations:52480,updated:"2 min ago",sentiment:{negative:55,neutral:27,positive:18},sentimentChange:8,insight:"Public conversation is currently leaning negative. Major concerns revolve around fairness, implementation and access to opportunities, while supportive conversations focus on representation and social equity.",audience:{geography:"Delhi NCR",language:"Hindi / Hinglish",age:"18–24 years",ageConfidence:"Medium",interests:"Students & job aspirants",topics:["Reservation","Jobs","Education","Equality"],platform:"X leads the discussion"},drivers:[{title:"Fairness & Equality",description:"Most people are debating fairness, equality and equal opportunities for all.",status:"Top concern"},{title:"Education & Admissions",description:"Large volume of discussion on college admissions, seat allocation and cutoff impact.",status:"Rising"},{title:"Employment Opportunities",description:"Debates around job reservation, private-sector inclusion and economic impact.",status:"Rising"},{title:"Government Policy",description:"Opinions on policy implementation, revisions and the legal framework.",status:"Stable"}],voices:[{quote:"Reservation is important for representation and giving equal opportunities to everyone.",label:"Supporting voice",tone:"supporting"},{quote:"Merit is being compromised. There should be a balance between both.",label:"Concerned voice",tone:"concerned"},{quote:"What about economic background? Shouldn’t that matter more than caste?",label:"Neutral / questioning",tone:"neutral"}],trends:[{time:"06:00",volume:6200,sentiment:47},{time:"09:00",volume:7100,sentiment:48},{time:"12:00",volume:8400,sentiment:50},{time:"15:00",volume:10600,sentiment:51},{time:"18:00",volume:13100,sentiment:54},{time:"Now",volume:15480,sentiment:55}],confidence:{sources:["X","YouTube","Telegram","Reddit"],qualified:28410,lowSignal:6281,level:"High"},network:{nodes:[{id:"students",label:"Student communities",group:"origin",size:36},{id:"education",label:"Education forums",group:"amplifier",size:28},{id:"policy",label:"Policy discussions",group:"amplifier",size:32},{id:"public",label:"General public",group:"audience",size:42},{id:"jobs",label:"Job aspirants",group:"audience",size:26}],edges:[{source:"students",target:"education",weight:8},{source:"students",target:"policy",weight:6},{source:"education",target:"public",weight:7},{source:"policy",target:"public",weight:9},{source:"jobs",target:"policy",weight:5}]}};
